using System.Collections.Generic;

namespace ActivityViewer.Core.Localization
{
    internal static partial class Texts
    {
        internal static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
        {
            ["lang.name"] = "English",
            ["common.value"] = "Value {0}",

            ["col.Time"] = "Time",
            ["col.Player"] = "Player",
            ["col.Id"] = "ID",
            ["col.Event"] = "Event",
            ["col.Target"] = "Target or attacker",
            ["col.Total"] = "Total",
            ["col.Types"] = "Types",
            ["col.HealthAfter"] = "Health after",
            ["col.X"] = "X",
            ["col.Y"] = "Y",
            ["col.Z"] = "Z",
            ["col.Item"] = "Item",
            ["col.Quantity"] = "Quantity",
            ["col.Quality"] = "Quality",
            ["col.Crafter"] = "Crafter",
            ["col.Origin"] = "Origin",
            ["col.Destination"] = "Destination",
            ["col.Object"] = "Object",
            ["col.Result"] = "Result",
            ["col.Info"] = "Info",
            ["col.UsedItem"] = "Used item",
            ["col.Actions"] = "Actions",
            ["col.Events"] = "Events",
            ["col.Objects"] = "Objects",
            ["col.Speed"] = "Speed",
            ["col.Distance"] = "Distance",
            ["col.Seconds"] = "Seconds",
            ["col.From"] = "From",
            ["col.To"] = "To",

            ["damage.damage"] = "Damage",
            ["damage.blunt"] = "Blunt",
            ["damage.slash"] = "Slash",
            ["damage.pierce"] = "Pierce",
            ["damage.fire"] = "Fire",
            ["damage.frost"] = "Frost",
            ["damage.lightning"] = "Lightning",
            ["damage.poison"] = "Poison",
            ["damage.spirit"] = "Spirit",
            ["damage.chop"] = "Chop",
            ["damage.pickaxe"] = "Pickaxe",

            ["route.ground"] = "Ground",
            ["route.inventory"] = "Inventory",
            ["route.consumed"] = "Consumed",

            ["result.success"] = "Success",
            ["result.failure"] = "Failure",

            ["cache.describe"] = "Copy from {0} ({1:0.0} MB)",
            ["cache.nested"] = "The new folder can't be inside the current copies folder (or the other way around).",

            ["download.worldNotFound"] = "World not found on the server: {0}.",
            ["download.walChanged"] = "The -wal file changed during the download ({0}).",
            ["download.dbChanged"] = "The database changed during the download.",
            ["download.checkFailed"] = "Integrity check failed: {0}",
            ["download.success"] = "Copy downloaded successfully.",
            ["download.usingPrevious"] = "Using the copy from {0}.",
            ["download.noPrevious"] = "No previous copy available.",
            ["download.failed"] = "Could not get a consistent copy after 3 attempts. {0} Last problem: {1}",

            ["db.notFound"] = "File not found.",
            ["db.notSqlite"] = "The file is not a valid SQLite database: {0}",
            ["db.notActivity"] = "The file is not a Vikings_ActivityLog database.",
            ["db.newer"] = "This database comes from a newer version of the mod. Update the Viewer.",

            ["profile.nameRequired"] = "Enter the profile name.",
            ["profile.hostRequired"] = "Enter the host.",
            ["profile.portInvalid"] = "Invalid port (1 to 65535).",
            ["profile.userRequired"] = "Enter the user name.",
            ["profile.folderRequired"] = "Enter the remote folder.",

            ["sqlite.openFailed"] = "Could not open {0}: {1}",
            ["sqlite.badParameter"] = "Unsupported parameter type: {0}",
            ["sqlite.missingResource"] = "The e_sqlite3.dll resource is missing from the program.",

            ["transfer.downloadFailed"] = "Failed to download {0}.",
            ["transfer.hostKeyChanged"] = "The SFTP server key changed since the last connection. This may indicate an attack. If the change is expected (server reinstalled), clear the trusted key in the profile.",

            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.save"] = "Save",
            ["common.search"] = "Search",
            ["common.savePassword"] = "Save password on this PC (encrypted by Windows)",

            ["app.unhandled"] = "An unexpected error occurred:\n\n{0}",
            ["log.unhandled"] = "Unhandled UI error",
            ["log.openDatabase"] = "Open database {0}",
            ["log.connection"] = "Connection to {0}",
            ["log.export"] = "Export {0}",
            ["log.testConnection"] = "Connection test to {0}",

            ["sidebar.source"] = "SOURCE",
            ["sidebar.server"] = "Server",
            ["sidebar.world"] = "World",
            ["sidebar.download"] = "Download",
            ["sidebar.downloadHint"] = "Download the latest copy of the server database",
            ["sidebar.manageServers"] = "Manage servers",
            ["sidebar.listWorlds"] = "List the server's worlds",
            ["sidebar.noDatabase"] = "No database open.",
            ["sidebar.filters"] = "FILTERS",
            ["main.settings"] = "Settings",

            ["settings.title"] = "Settings",
            ["settings.language"] = "LANGUAGE",
            ["settings.cacheFolder"] = "FOLDER FOR DOWNLOADED COPIES",
            ["settings.change"] = "Change...",
            ["settings.useDefault"] = "Use default",
            ["settings.pickFolder"] = "Choose the folder for downloaded copies",
            ["settings.copiesTitle"] = "DOWNLOADED COPIES",
            ["settings.copies"] = "{0} world(s), {1:0.0} MB on this PC.",
            ["settings.clearCurrent"] = "Clear current copy",
            ["settings.clearAll"] = "Clear all",
            ["settings.localOnly"] = "Clearing only deletes the copies downloaded to this PC. The databases on the servers are not changed.",
            ["settings.noCurrent"] = "No downloaded copy is open right now.",
            ["settings.clearCurrentQuestion"] = "Delete the downloaded copy of {0} on this PC?\n\nThe database on the server is not changed.",
            ["settings.clearAllQuestion"] = "Delete all downloaded copies on this PC ({0} world(s))?\n\nThe databases on the servers are not changed.",
            ["settings.cleared"] = "Copies deleted: {0}.",
            ["settings.moveQuestion"] = "Move {0} copy(ies) to the new folder?\n\n{1}",
            ["settings.moved"] = "Folder changed. Copies moved: {0}.",
            ["settings.moveFailed"] = "Could not move the copies:\n\n{0}",

            ["main.openLocal"] = "Open local file...",
            ["main.player"] = "Player",
            ["main.from"] = "From",
            ["main.fromHint"] = "yyyy-MM-dd or yyyy-MM-dd HH:mm (empty = no limit)",
            ["main.to"] = "To",
            ["main.toHint"] = "yyyy-MM-dd or yyyy-MM-dd HH:mm (date only = until the end of the day)",
            ["main.analyze"] = "Analyze",
            ["main.analyzeHint"] = "Reloads players and suggestions and runs every tab's search with the current filters.",
            ["main.clearFilters"] = "Clear filters",
            ["main.allPlayers"] = "All players",
            ["main.profilesCorrupt"] = "The profiles file was invalid and was kept as:\n{0}",
            ["main.welcome"] = "Choose a profile and a world, or open a local file.",
            ["main.noLocalCopy"] = "No local copy. Click Download.",
            ["main.worldNotDownloaded"] = "The world {0} has not been downloaded yet.",
            ["main.openFirst"] = "Open a database first: choose a world and click Download, or open a local file.",
            ["main.wait"] = "Wait for the current operation to finish.",
            ["main.analysisCancelled"] = "Analysis cancelled: {0}",
            ["main.analysisDone"] = "Analysis finished: {0}",
            ["main.chooseProfile"] = "Choose or create a server first (pencil button next to Server).",
            ["main.connecting"] = "Connecting to {0}...",
            ["main.noWorlds"] = "No world found in {0}.",
            ["main.worldsFound"] = "{0} world(s) found on the server.",
            ["main.chooseProfileWorld"] = "Choose a server and a world. Use the refresh button next to World to see the server's worlds.",
            ["main.downloading"] = "Downloading {0}...",
            ["main.downloadProgress"] = "Downloading (attempt {0}/{1}): {2:0.0} of {3:0.0} MB",
            ["main.operationCancelled"] = "Operation cancelled.",
            ["main.connectionFailed"] = "Connection to {0} failed:\n\n{1}",
            ["main.openDialogTitle"] = "Open a Vikings_ActivityLog database",
            ["main.openDialogFilter"] = "SQLite database (*.db)|*.db|All files (*.*)|*.*",
            ["main.localFile"] = "Local file: {0}",
            ["main.playerNotFound"] = "Player not found: {0}. Choose a player from the list.",
            ["main.invalidFrom"] = "Invalid date in \"From\". Use {0}.",
            ["main.invalidTo"] = "Invalid date in \"To\". Use {0}.",
            ["main.fromAfterTo"] = "The \"From\" date is after the \"To\" date.",
            ["main.rowsTime"] = "{0:N0} row(s) in {1:0.00} s.",
            ["main.searchCancelled"] = "Search cancelled.",
            ["main.dbChangedBeforeExport"] = "The database was changed after this search. Run the search again before exporting.",
            ["main.exporting"] = "Exporting...",
            ["main.exported"] = "Exported: {0}",
            ["main.exportCancelled"] = "Export cancelled.",
            ["main.writeFailed"] = "Could not write the file:\n\n{0}",
            ["main.cancelling"] = "Cancelling...",
            ["main.unexpected"] = "Unexpected error: {0}",
            ["main.detailsIn"] = "\n\nDetails in:\n{0}",
            ["main.errorStatus"] = "Error: {0}",
            ["main.restartQuestion"] = "The language will be applied when the program restarts.\n\nRestart now?",
            ["main.restartLater"] = "The new language will be applied the next time the program opens.",

            ["tab.damage"] = "Damage",
            ["tab.items"] = "Items",
            ["tab.frequency"] = "Actions/sec",
            ["tab.speed"] = "Speed",
            ["tab.interactions"] = "Interactions",

            ["damage.min"] = "Min. damage:",
            ["damage.target"] = "Target:",
            ["damage.attacker"] = "Attacker:",
            ["damage.searching"] = "Searching damage...",
            ["damage.invalidMin"] = "Invalid minimum damage. Use a number, for example 50 or 12.5.",
            ["items.item"] = "Item:",
            ["items.min"] = "Min. qty:",
            ["items.searching"] = "Searching items...",
            ["items.invalidMin"] = "Invalid minimum quantity. Use a whole number.",
            ["items.noEvents"] = "Select at least one event type.",
            ["frequency.limit"] = "Max. actions/sec:",
            ["frequency.hint"] = "Counts each player's Pickup, Place, Remove, Interact, Drop and Move in 1-second windows.",
            ["frequency.searching"] = "Analyzing actions per second...",
            ["frequency.invalidLimit"] = "Invalid limit. Use a whole number from 1.",
            ["speed.limit"] = "Max. speed (u/s):",
            ["speed.hint"] = "Uses only events with the player's own position; ignores teleport, death, respawn and reconnection.",
            ["speed.searching"] = "Analyzing speed...",
            ["speed.invalidLimit"] = "Invalid speed. Use a number greater than zero, for example 150.",
            ["interactions.object"] = "Object:",
            ["interactions.result"] = "Result:",
            ["interactions.any"] = "All",
            ["interactions.searching"] = "Searching interactions...",

            ["result.export"] = "Export...",
            ["result.copyId"] = "Copy ID",
            ["result.none"] = "No search yet.",
            ["result.truncated"] = " Result too large, refine the filter (showing the first {0:N0}; Export writes everything).",
            ["result.idCopied"] = "ID copied: {0}",
            ["result.clipboardFailed"] = "Could not copy to the clipboard. Try again.",
            ["result.exportTitle"] = "Export result",
            ["result.exportFilter"] = "CSV for Excel (*.csv)|*.csv|Text (*.txt)|*.txt",
            ["result.fileName"] = "report",

            ["password.title"] = "Password",
            ["password.savedFailed"] = "The saved password could not be read on this PC or Windows user. ",
            ["password.prompt"] = "Enter the password for profile \"{0}\".",
            ["password.empty"] = "Enter the password.",

            ["profiles.title"] = "Server profiles",
            ["profiles.new"] = "New",
            ["profiles.delete"] = "Delete",
            ["profiles.name"] = "Name:",
            ["profiles.protocol"] = "Protocol:",
            ["profiles.host"] = "Host:",
            ["profiles.port"] = "Port:",
            ["profiles.user"] = "User:",
            ["profiles.password"] = "Password:",
            ["profiles.folder"] = "Remote folder:",
            ["profiles.folderHint"] = "The server's -savedir folder followed by /Vikings_ActivityLog. E.g.: /SAVE/Vikings_ActivityLog",
            ["profiles.trust"] = "Trust:",
            ["profiles.clearTrust"] = "Clear trust",
            ["profiles.test"] = "Test connection",
            ["profiles.passwordSaved"] = "Password saved. Leave blank to keep it.",
            ["profiles.noPassword"] = "No password saved.",
            ["profiles.duplicate"] = "A profile with this name already exists.",
            ["profiles.saved"] = "Profile saved.",
            ["profiles.deleteQuestion"] = "Delete profile \"{0}\"? Downloaded copies are not deleted.",
            ["profiles.trustCleared"] = "Trust removed. Click Save.",
            ["profiles.trustedCertificate"] = "Trusted certificate: {0}",
            ["profiles.trustedKey"] = "Trusted SFTP key: {0}",
            ["profiles.noTrust"] = "No trusted certificate or key saved.",
            ["profiles.passwordForTest"] = "Enter the password to test the connection.",
            ["profiles.testing"] = "Testing connection...",
            ["profiles.noDb"] = "No .db file found in {0}.",
            ["profiles.worldsList"] = "{0} world(s): {1}",
            ["profiles.connectionOk"] = "Connection OK.",
            ["profiles.saveTrustHint"] = "\n\nClick Save to keep the trust for this server.",
            ["profiles.connectionFailed"] = "Connection failed:\n\n{0}",
            ["profiles.connectionFailedStatus"] = "Connection failed.",

            ["trust.title"] = "Confirm server",
            ["trust.changed"] = "WARNING: the server certificate CHANGED since the last connection.\n\n",
            ["trust.unknown"] = "The server's TLS certificate is not recognized by Windows.\n\n",
            ["trust.certificate"] = "Server: {0}\nCertificate: {1}\nThumbprint: {2}\n\nTrust this certificate?",
            ["trust.hostKey"] = "First SFTP connection to this server.\n\nServer: {0}\nServer key (SHA256): {1}\n\nTrust this key?",
        };
    }
}
