using System.Collections.Generic;

namespace ActivityViewer.Core.Localization
{
    internal static partial class Texts
    {
        internal static readonly IReadOnlyDictionary<string, string> Portuguese = new Dictionary<string, string>
        {
            ["lang.name"] = "Português",
            ["common.value"] = "Valor {0}",

            ["col.Time"] = "Data",
            ["col.Player"] = "Jogador",
            ["col.Id"] = "ID",
            ["col.Event"] = "Evento",
            ["col.Target"] = "Alvo ou atacante",
            ["col.Total"] = "Total",
            ["col.Types"] = "Tipos",
            ["col.HealthAfter"] = "Vida após",
            ["col.X"] = "X",
            ["col.Y"] = "Y",
            ["col.Z"] = "Z",
            ["col.Item"] = "Item",
            ["col.Quantity"] = "Quantidade",
            ["col.Quality"] = "Qualidade",
            ["col.Crafter"] = "Criador",
            ["col.Origin"] = "Origem",
            ["col.Destination"] = "Destino",
            ["col.Object"] = "Objeto",
            ["col.Result"] = "Resultado",
            ["col.Info"] = "Info",
            ["col.UsedItem"] = "Item usado",
            ["col.Actions"] = "Ações",
            ["col.Events"] = "Eventos",
            ["col.Objects"] = "Objetos",
            ["col.Speed"] = "Velocidade",
            ["col.Distance"] = "Distância",
            ["col.Seconds"] = "Segundos",
            ["col.From"] = "De",
            ["col.To"] = "Para",

            ["damage.damage"] = "Dano",
            ["damage.blunt"] = "Contundente",
            ["damage.slash"] = "Corte",
            ["damage.pierce"] = "Perfuração",
            ["damage.fire"] = "Fogo",
            ["damage.frost"] = "Gelo",
            ["damage.lightning"] = "Raio",
            ["damage.poison"] = "Veneno",
            ["damage.spirit"] = "Espírito",
            ["damage.chop"] = "Corte de árvore",
            ["damage.pickaxe"] = "Mineração",

            ["route.ground"] = "Chão",
            ["route.inventory"] = "Inventário",
            ["route.consumed"] = "Consumido",

            ["result.success"] = "Sucesso",
            ["result.failure"] = "Falha",

            ["cache.describe"] = "Cópia de {0} ({1:0.0} MB)",
            ["cache.nested"] = "A nova pasta não pode ficar dentro da pasta atual das cópias (nem o contrário).",

            ["download.worldNotFound"] = "Mundo não encontrado no servidor: {0}.",
            ["download.walChanged"] = "O arquivo -wal mudou durante o download ({0}).",
            ["download.dbChanged"] = "O banco mudou durante o download.",
            ["download.checkFailed"] = "Verificação de integridade falhou: {0}",
            ["download.success"] = "Cópia baixada com sucesso.",
            ["download.usingPrevious"] = "Usando a cópia de {0}.",
            ["download.noPrevious"] = "Nenhuma cópia anterior disponível.",
            ["download.failed"] = "Não foi possível obter uma cópia consistente após 3 tentativas. {0} Último problema: {1}",

            ["db.notFound"] = "Arquivo não encontrado.",
            ["db.notSqlite"] = "O arquivo não é um banco SQLite válido: {0}",
            ["db.notActivity"] = "O arquivo não é um banco do Vikings_ActivityLog.",
            ["db.newer"] = "Banco de uma versão mais nova do mod. Atualize o Viewer.",

            ["profile.nameRequired"] = "Informe o nome do perfil.",
            ["profile.hostRequired"] = "Informe o host.",
            ["profile.portInvalid"] = "Porta inválida (1 a 65535).",
            ["profile.userRequired"] = "Informe o usuário.",
            ["profile.folderRequired"] = "Informe a pasta remota.",

            ["sqlite.openFailed"] = "Não foi possível abrir {0}: {1}",
            ["sqlite.badParameter"] = "Tipo de parâmetro não suportado: {0}",
            ["sqlite.missingResource"] = "Recurso e_sqlite3.dll ausente no programa.",

            ["transfer.downloadFailed"] = "Falha ao baixar {0}.",
            ["transfer.hostKeyChanged"] = "A chave do servidor SFTP mudou desde a última conexão. Isso pode indicar um ataque. Se a mudança for esperada (servidor reinstalado), limpe a chave confiável no perfil.",

            ["common.cancel"] = "Cancelar",
            ["common.close"] = "Fechar",
            ["common.save"] = "Salvar",
            ["common.search"] = "Buscar",
            ["common.savePassword"] = "Salvar senha neste PC (criptografada pelo Windows)",

            ["app.unhandled"] = "Ocorreu um erro inesperado:\n\n{0}",
            ["log.unhandled"] = "Erro não tratado na interface",
            ["log.openDatabase"] = "Abrir banco {0}",
            ["log.connection"] = "Conexão com {0}",
            ["log.export"] = "Exportar {0}",
            ["log.testConnection"] = "Teste de conexão com {0}",

            ["sidebar.source"] = "FONTE",
            ["sidebar.server"] = "Servidor",
            ["sidebar.world"] = "Mundo",
            ["sidebar.download"] = "Baixar",
            ["sidebar.downloadHint"] = "Baixar a cópia mais recente do banco do servidor",
            ["sidebar.manageServers"] = "Gerenciar servidores",
            ["sidebar.listWorlds"] = "Listar os mundos do servidor",
            ["sidebar.noDatabase"] = "Nenhum banco aberto.",
            ["sidebar.filters"] = "FILTROS",
            ["main.settings"] = "Configurações",

            ["settings.title"] = "Configurações",
            ["settings.language"] = "IDIOMA",
            ["settings.cacheFolder"] = "PASTA DAS CÓPIAS BAIXADAS",
            ["settings.change"] = "Alterar...",
            ["settings.useDefault"] = "Usar padrão",
            ["settings.pickFolder"] = "Escolha a pasta para as cópias baixadas",
            ["settings.copiesTitle"] = "CÓPIAS BAIXADAS",
            ["settings.copies"] = "{0} mundo(s), {1:0.0} MB neste PC.",
            ["settings.clearCurrent"] = "Limpar cópia atual",
            ["settings.clearAll"] = "Limpar todas",
            ["settings.localOnly"] = "Limpar apaga só as cópias baixadas neste PC. Os bancos nos servidores não são alterados.",
            ["settings.noCurrent"] = "Nenhuma cópia baixada está aberta agora.",
            ["settings.clearCurrentQuestion"] = "Apagar a cópia baixada de {0} neste PC?\n\nO banco no servidor não é alterado.",
            ["settings.clearAllQuestion"] = "Apagar todas as cópias baixadas neste PC ({0} mundo(s))?\n\nOs bancos nos servidores não são alterados.",
            ["settings.cleared"] = "Cópias apagadas: {0}.",
            ["settings.moveQuestion"] = "Mover {0} cópia(s) para a nova pasta?\n\n{1}",
            ["settings.moved"] = "Pasta alterada. Cópias movidas: {0}.",
            ["settings.moveFailed"] = "Não foi possível mover as cópias:\n\n{0}",

            ["main.openLocal"] = "Abrir arquivo local...",
            ["main.player"] = "Jogador",
            ["main.from"] = "De",
            ["main.fromHint"] = "dd/MM/aaaa ou dd/MM/aaaa HH:mm (vazio = sem limite)",
            ["main.to"] = "Até",
            ["main.toHint"] = "dd/MM/aaaa ou dd/MM/aaaa HH:mm (só a data = até o fim do dia)",
            ["main.analyze"] = "Analisar",
            ["main.analyzeHint"] = "Recarrega jogadores e sugestões e executa a busca de todas as abas com os filtros atuais.",
            ["main.clearFilters"] = "Limpar filtros",
            ["main.allPlayers"] = "Todos os jogadores",
            ["main.profilesCorrupt"] = "O arquivo de perfis estava inválido e foi guardado como:\n{0}",
            ["main.welcome"] = "Escolha um perfil e um mundo, ou abra um arquivo local.",
            ["main.noLocalCopy"] = "Sem cópia local. Clique em Baixar.",
            ["main.worldNotDownloaded"] = "O mundo {0} ainda não foi baixado.",
            ["main.openFirst"] = "Abra um banco primeiro: escolha um mundo e clique em Baixar, ou abra um arquivo local.",
            ["main.wait"] = "Aguarde a operação atual terminar.",
            ["main.analysisCancelled"] = "Análise cancelada: {0}",
            ["main.analysisDone"] = "Análise concluída: {0}",
            ["main.chooseProfile"] = "Escolha ou crie um servidor primeiro (botão de lápis ao lado de Servidor).",
            ["main.connecting"] = "Conectando a {0}...",
            ["main.noWorlds"] = "Nenhum mundo encontrado em {0}.",
            ["main.worldsFound"] = "{0} mundo(s) encontrado(s) no servidor.",
            ["main.chooseProfileWorld"] = "Escolha um servidor e um mundo. Use o botão de atualizar ao lado de Mundo para ver os mundos do servidor.",
            ["main.downloading"] = "Baixando {0}...",
            ["main.downloadProgress"] = "Baixando (tentativa {0}/{1}): {2:0.0} de {3:0.0} MB",
            ["main.operationCancelled"] = "Operação cancelada.",
            ["main.connectionFailed"] = "Falha na conexão com {0}:\n\n{1}",
            ["main.openDialogTitle"] = "Abrir banco do Vikings_ActivityLog",
            ["main.openDialogFilter"] = "Banco SQLite (*.db)|*.db|Todos os arquivos (*.*)|*.*",
            ["main.localFile"] = "Arquivo local: {0}",
            ["main.playerNotFound"] = "Jogador não encontrado: {0}. Escolha um jogador da lista.",
            ["main.invalidFrom"] = "Data inválida em \"De\". Use {0}.",
            ["main.invalidTo"] = "Data inválida em \"Até\". Use {0}.",
            ["main.fromAfterTo"] = "A data em \"De\" é posterior à data em \"Até\".",
            ["main.rowsTime"] = "{0:N0} linha(s) em {1:0.00} s.",
            ["main.searchCancelled"] = "Busca cancelada.",
            ["main.dbChangedBeforeExport"] = "O banco foi trocado depois desta busca. Refaça a busca antes de exportar.",
            ["main.exporting"] = "Exportando...",
            ["main.exported"] = "Exportado: {0}",
            ["main.exportCancelled"] = "Exportação cancelada.",
            ["main.writeFailed"] = "Não foi possível gravar o arquivo:\n\n{0}",
            ["main.cancelling"] = "Cancelando...",
            ["main.unexpected"] = "Erro inesperado: {0}",
            ["main.detailsIn"] = "\n\nDetalhes em:\n{0}",
            ["main.errorStatus"] = "Erro: {0}",
            ["main.restartQuestion"] = "O idioma será aplicado ao reiniciar o programa.\n\nReiniciar agora?",
            ["main.restartLater"] = "O novo idioma será aplicado na próxima vez que o programa abrir.",

            ["tab.damage"] = "Dano",
            ["tab.items"] = "Itens",
            ["tab.frequency"] = "Ações/seg",
            ["tab.speed"] = "Velocidade",
            ["tab.interactions"] = "Interações",

            ["damage.min"] = "Dano mín.:",
            ["damage.target"] = "Alvo:",
            ["damage.attacker"] = "Atacante:",
            ["damage.searching"] = "Buscando dano...",
            ["damage.invalidMin"] = "Dano mínimo inválido. Use um número, por exemplo 50 ou 12,5.",
            ["items.item"] = "Item:",
            ["items.min"] = "Qtd. mín.:",
            ["items.searching"] = "Buscando itens...",
            ["items.invalidMin"] = "Quantidade mínima inválida. Use um número inteiro.",
            ["items.noEvents"] = "Marque pelo menos um tipo de evento.",
            ["frequency.limit"] = "Ações/seg máx.:",
            ["frequency.hint"] = "Conta Pickup, Place, Remove, Interact, Drop e Move de cada jogador em janelas de 1 segundo.",
            ["frequency.searching"] = "Analisando ações por segundo...",
            ["frequency.invalidLimit"] = "Limite inválido. Use um número inteiro a partir de 1.",
            ["speed.limit"] = "Velocidade máx. (u/s):",
            ["speed.hint"] = "Usa só eventos com a posição do próprio jogador; ignora teleporte, morte, respawn e reconexão.",
            ["speed.searching"] = "Analisando velocidade...",
            ["speed.invalidLimit"] = "Velocidade inválida. Use um número maior que zero, por exemplo 150.",
            ["interactions.object"] = "Objeto:",
            ["interactions.result"] = "Resultado:",
            ["interactions.any"] = "Todos",
            ["interactions.searching"] = "Buscando interações...",

            ["result.export"] = "Exportar...",
            ["result.copyId"] = "Copiar ID",
            ["result.none"] = "Nenhuma busca realizada.",
            ["result.truncated"] = " Resultado muito grande, refine o filtro (mostrando as primeiras {0:N0}; Exportar grava tudo).",
            ["result.idCopied"] = "ID copiado: {0}",
            ["result.clipboardFailed"] = "Não foi possível copiar para a área de transferência. Tente novamente.",
            ["result.exportTitle"] = "Exportar resultado",
            ["result.exportFilter"] = "CSV para Excel (*.csv)|*.csv|Texto (*.txt)|*.txt",
            ["result.fileName"] = "relatorio",

            ["password.title"] = "Senha",
            ["password.savedFailed"] = "A senha salva não pôde ser lida neste PC ou usuário do Windows. ",
            ["password.prompt"] = "Digite a senha do perfil \"{0}\".",
            ["password.empty"] = "Digite a senha.",

            ["profiles.title"] = "Perfis de servidor",
            ["profiles.new"] = "Novo",
            ["profiles.delete"] = "Excluir",
            ["profiles.name"] = "Nome:",
            ["profiles.protocol"] = "Protocolo:",
            ["profiles.host"] = "Host:",
            ["profiles.port"] = "Porta:",
            ["profiles.user"] = "Usuário:",
            ["profiles.password"] = "Senha:",
            ["profiles.folder"] = "Pasta remota:",
            ["profiles.folderHint"] = "Pasta do -savedir do servidor seguida de /Vikings_ActivityLog. Ex.: /SAVE/Vikings_ActivityLog",
            ["profiles.trust"] = "Confiança:",
            ["profiles.clearTrust"] = "Limpar confiança",
            ["profiles.test"] = "Testar conexão",
            ["profiles.passwordSaved"] = "Senha salva. Deixe em branco para manter.",
            ["profiles.noPassword"] = "Nenhuma senha salva.",
            ["profiles.duplicate"] = "Já existe um perfil com esse nome.",
            ["profiles.saved"] = "Perfil salvo.",
            ["profiles.deleteQuestion"] = "Excluir o perfil \"{0}\"? As cópias já baixadas não são apagadas.",
            ["profiles.trustCleared"] = "Confiança removida. Clique em Salvar.",
            ["profiles.trustedCertificate"] = "Certificado confiável: {0}",
            ["profiles.trustedKey"] = "Chave SFTP confiável: {0}",
            ["profiles.noTrust"] = "Nenhum certificado ou chave confiável salvo.",
            ["profiles.passwordForTest"] = "Digite a senha para testar a conexão.",
            ["profiles.testing"] = "Testando conexão...",
            ["profiles.noDb"] = "Nenhum arquivo .db encontrado em {0}.",
            ["profiles.worldsList"] = "{0} mundo(s): {1}",
            ["profiles.connectionOk"] = "Conexão OK.",
            ["profiles.saveTrustHint"] = "\n\nClique em Salvar para guardar a confiança neste servidor.",
            ["profiles.connectionFailed"] = "Falha na conexão:\n\n{0}",
            ["profiles.connectionFailedStatus"] = "Falha na conexão.",

            ["trust.title"] = "Confirmar servidor",
            ["trust.changed"] = "ATENÇÃO: o certificado do servidor MUDOU desde a última conexão.\n\n",
            ["trust.unknown"] = "O certificado TLS do servidor não é reconhecido pelo Windows.\n\n",
            ["trust.certificate"] = "Servidor: {0}\nCertificado: {1}\nImpressão digital: {2}\n\nConfiar neste certificado?",
            ["trust.hostKey"] = "Primeira conexão SFTP com este servidor.\n\nServidor: {0}\nChave do servidor (SHA256): {1}\n\nConfiar nesta chave?",
        };
    }
}
